diplom/djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('your_app/', include('main.urls')),
]

diplom/main/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from . import views
from .views import send_invoice_to_supplier, supplier_orders_view, update_order_status
from allauth.socialaccount.views import SignupView

urlpatterns = [
    path('accounts/social/signup/google/', SignupView.as_view(), name='social_account_signup'),
    path('accounts/', include('allauth.urls')),
    path('', views.index_view, name='Home'),
    path('register/', views.register, name='register'),
    path('api/v1/drf-auth/', include('rest_framework.urls')),
    path('accounts/profile/', views.personal_account, name='personal-account'),
    path('logout/', views.logout_view, name='logout'),
    path('import_yaml/', views.import_yaml, name='import-yaml'),
    path('add_to_cart/<int:good_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('api/v1/drf-auth/logout/', LogoutView.as_view(), name='api-logout'),
    path('send-invoice/', send_invoice_to_supplier, name='send_invoice_to_supplier'),
    path('supplier/orders/', supplier_orders_view, name='supplier_orders'),
    path('update_order_status/', update_order_status, name='update_order_status'),
]

diplom/main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User
#Модель Пользователи
from djangoProject import settings


class CustomUser(AbstractUser):
    account_type = models.CharField(max_length=100, verbose_name='Тип аккаунта')

    def __str__(self):
        return self.username

    class Meta:
        unique_together = ('username',)

# Модель магазина
class Shop(models.Model):
    username = models.CharField(max_length=256)
    name = models.CharField(max_length=256)
    accepting_orders = models.BooleanField(default=True)  # Новое поле

    def __str__(self):
        return self.name


# Модель категории
class Category(models.Model):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE, related_name='categories')
    name = models.CharField(max_length=100)
    category_id = models.CharField(max_length=100)

    def __str__(self):
        return self.name


# Модель товаров
class Good(models.Model):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE, related_name='goods', null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='goods', null=True, blank=True)
    model = models.CharField(max_length=100, null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    price_rrc = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    quantity = models.IntegerField(null=True, blank=True)
    parameters = models.TextField(null=True, blank=True)
    characteristics = models.JSONField(null=True, blank=True)

    def __str__(self):
        return self.name


# Модель Корзина
class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)  # Связь с моделью Category
    model_name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=100)
    username = models.TextField()
    supplier_name = models.TextField()
    Address_street = models.TextField()

    def __str__(self):
        return self.category.name + " " + self.model_name

diplom/main/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Good

User = get_user_model()

class AddToCartForm(forms.Form):
    characteristics = forms.JSONField(required=False)  # Добавьте это поле

class RegisterUserForm(forms.ModelForm):
    username = forms.CharField(label="Логин")
    email = forms.EmailField(label="E-mail")
    first_name = forms.CharField(label="Имя")
    last_name = forms.CharField(label="Фамилия")
    password = forms.CharField(label="Пароль", widget=forms.PasswordInput())
    password2 = forms.CharField(label="Повтор пароля", widget=forms.PasswordInput())
    account_type = forms.CharField(label="Тип аккаунта")

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password', 'password2', 'account_type']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("Пароли не совпадают")
        return cd['password']

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже есть")
        return email

diplom/main/views.py
import ast
import yaml
from .tasks import send_invoice_to_supplier_task, update_order_status_task
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from rest_framework import status
from rest_framework.decorators import api_view, throttle_classes
from rest_framework.response import Response
from .forms import RegisterUserForm
from .models import Good, Cart, Category, Shop, CustomUser
from .serializers import GoodSerializer, UserCartSerializer, SupplierCartSerializer
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Cart
from rest_framework.throttling import UserRateThrottle

class MyThrottle(UserRateThrottle):
    scope = 'my_throttle'
    rate = '5/day'  # Пять запросов в день

@api_view(['POST'])
@throttle_classes([MyThrottle])
def send_invoice_to_supplier(request):
    """
    Отправить счет поставщику.
    """
    if request.method == 'POST':
        user_id = request.user.id
        send_invoice_to_supplier_task.delay(user_id)
        return redirect('personal-account')
    else:
        return Response(status=status.HTTP_405_METHOD_NOT_ALLOWED)

@csrf_exempt
@api_view(['POST'])
@throttle_classes([MyThrottle])
def update_order_status(request):
    """
    Обновить статус заказа.
    """
    if request.method == "POST":
        order_id = request.POST.get("order_id")
        next_status = request.POST.get("next_status")
        update_order_status_task.delay(order_id, next_status)
        return JsonResponse({"success": True})
    else:
        return JsonResponse({"success": False, "error": "Метод не разрешен"})

def register(request):
    """
    Регистрация нового пользователя.
    """
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])  # Хеширование пароля
            user.save()
            return redirect('Home')  # Перенаправление на главную страницу после успешной регистрации
    else:
        form = RegisterUserForm()
    return render(request, 'register.html', {'form': form})

@api_view(['GET'])
def index_view(request):
    """
    Отображение главной страницы.
    """
    current_user = request.user
    if current_user.is_authenticated:
        account_type = current_user.account_type
    else:
        account_type = None
    goods = Good.objects.all()
    for product in goods:
        product.formatted_parameters = format_parameters_for_template(product.parameters)
    context = {'account_type': account_type, 'goods': goods}
    return render(request, 'base.html', context)

@login_required
def personal_account(request):
    """
    Персональный кабинет пользователя.
    """
    current_user = request.user
    account_type = current_user.account_type
    user_products = Good.objects.filter(shop__username=current_user.username)
    for product in user_products:
        product.formatted_parameters = format_parameters_for_template(product.parameters)
    user_cart = Cart.objects.filter(user=current_user)

    # Получаем заказы поставщика
    supplier_orders = Cart.objects.filter(username=current_user.username)

    context = {
        'account_type': account_type,
        'user_products': user_products,
        'user_cart': user_cart,
        'supplier_orders': supplier_orders,  # Добавляем заказы поставщика в контекст
    }
    return render(request, 'personal_account.html', context)

def supplier_orders_view(request):
    """
    Отображение заказов поставщика.
    """
    if request.user.is_authenticated and request.user.account_type == 'Поставщик':
        supplier_orders = Cart.objects.filter(username=request.user.username)
        context = {'supplier_orders': supplier_orders}
        return render(request, 'supplier_orders.html', context)
    else:
        return redirect('login')  # Или другой URL для авторизации

@api_view(['POST', 'GET'])
@throttle_classes([MyThrottle])
def import_yaml(request):
    """
    Импорт данных из YAML-файла.
    """
    if request.method == 'POST' and request.FILES.get('yaml_file'):
        yaml_file = request.FILES['yaml_file']
        yaml_data = yaml.safe_load(yaml_file)
        shop_username = request.user.username
        shop_name = yaml_data.get('shop')
        shop, created = Shop.objects.get_or_create(username=shop_username, name=shop_name)
        categories_data = yaml_data.get('categories', [])
        for category_data in categories_data:
            category_id = category_data.get('id')
            category_name = category_data.get('name')
            category, created = Category.objects.get_or_create(shop=shop, category_id=category_id, defaults={'name': category_name})
        goods_data = yaml_data.get('goods', [])
        for good_data in goods_data:
            category_id = good_data['category']
            category = Category.objects.get(shop=shop, category_id=category_id)
            Good.objects.create(
                shop=shop,
                category=category,
                model=good_data['model'],
                name=good_data['name'],
                price=good_data['price'],
                price_rrc=good_data['price_rrc'],  # Убедитесь, что price_rrc устанавливается правильно
                quantity=good_data['quantity'],
                parameters=good_data['parameters']
            )
        return redirect('personal-account')
    elif request.method == 'GET':
        return render(request, 'import_yaml.html')

@api_view(['GET'])
def cart_list(request):
    """
    Получить список товаров в корзине пользователя.
    """
    carts = Cart.objects.filter(user=request.user)
    serializer = SupplierCartSerializer(carts, many=True)
    return Response(serializer.data)

@api_view(['POST'])
@login_required
def add_to_cart(request, good_id):
    """
    Добавить товар в корзину пользователя.
    """
    if request.method == 'POST':
        try:
            good = Good.objects.get(id=good_id)
            # Получаем магазин, к которому принадлежит товар
            shop = good.shop
            supplier_username = shop.username  # Получаем логин поставщика

            # Проверяем, был ли передан адрес доставки в запросе
            delivery_address = request.data.get('delivery_address')

            # Создаем словарь с данными для сериализатора
            data = {
                'user': request.user.id,
                'category': good.category.id,
                'model_name': good.name,
                'price': good.price,
                'status': 'В корзине',
                'username': supplier_username,  # Сохраняем логин поставщика
                'supplier_name': request.user.username,
                'Address_street': delivery_address  # Добавляем адрес доставки в данные
            }

            # Создаем сериализатор с переданными данными
            serializer = UserCartSerializer(data=data)
            if serializer.is_valid():
                serializer.save()
                # После успешного добавления товара в корзину производим перенаправление на главную страницу
                return redirect('Home')
            # Если сериализатор не валиден, возвращаем ошибку
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        except Good.DoesNotExist:
            return Response({"error": "Товар не найден"}, status=status.HTTP_404_NOT_FOUND)
    else:
        return Response(status=status.HTTP_405_METHOD_NOT_ALLOWED)

@api_view(['POST'])
@login_required
def remove_from_cart(request, cart_item_id):
    """
    Удалить товар из корзины пользователя.
    """
    # Получаем текущего пользователя
    current_user = request.user
    # Получаем товар из корзины по его ID
    try:
        cart_item = Cart.objects.get(pk=cart_item_id, user=current_user)
    except Cart.DoesNotExist:
        # Если товар не найден в корзине пользователя, перенаправляем его обратно
        return redirect('personal-account')

    # Удаляем товар из корзины
    cart_item.delete()

    # Перенаправляем пользователя обратно в личный кабинет
    return redirect('personal-account')

def format_parameters_for_template(parameters):
    """
    Форматирование параметров товара для шаблона.
    """
    formatted_parameters = ""
    try:
        parameters_dict = ast.literal_eval(parameters)
        for key, value in parameters_dict.items():
            formatted_parameters += f"<p>{key}: {value}</p>"
    except (ValueError, SyntaxError):
        formatted_parameters = parameters
    return formatted_parameters

@api_view(['GET'])
def good_list(request):
    """
    Получить список всех товаров.
    """
    goods = Good.objects.all()
    serializer = GoodSerializer(goods, many=True)
    return Response(serializer.data)

@api_view(['GET'])
def logout_view(request):
    """
    Выход пользователя из системы.
    """
    logout(request)
    return redirect('Home')

diplom/main/templates/Personal_account.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Личный кабинет</title>
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/Personal_account.css' %}">
</head>
<body>
<header>
    {% if account_type == 'Поставщик' %}
        <h1>Мои товары</h1>
        <div class="button-actions">
            <a href="/">Главная</a>
            <a href="{% url 'supplier_orders' %}">Мои заказы</a>
            <a href="/your_app/import_yaml/">Импорт товаров</a>
        </div>
    {% elif account_type == "Покупатель" %}
    <h1>Корзина</h1>
        <div class="button-actions">
            <a href="/">Магазин</a>
            <form action="{% url 'send_invoice_to_supplier' %}" method="post">
                {% csrf_token %}
                <button type="submit">Сделать заявку</button>
            </form>
        </div>
    {% endif %}
</header>
<main>
    <div class="product-list">
        {% if account_type == 'Поставщик' %}
            <ul>
                {% for product in user_products %}
                    <li>
                        <table>
                            <thead>
                                <tr>
                                    <th>Название</th>
                                    <th>Цена</th>
                                    <th>Рекомендуемая цена</th>
                                    <th>Модель товара</th>
                                    <th>Имя модели</th>
                                    <th>Количество</th>
                                    <th>Параметры</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>{{ product.name }}</td>
                                    <td>{{ product.price }}</td>
                                    <td>{{ product.price_rrc }}</td>
                                    <td>{{ product.model }}</td>
                                    <td>{{ product.name }}</td>
                                    <td>{{ product.quantity }}</td>
                                    <td>{{ product.formatted_parameters | safe }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </li>
                {% empty %}
                    <p>У вас пока нет товаров.</p>
                {% endfor %}
            </ul>
        {% elif account_type == 'Покупатель' %}
            <h1>Товары в корзине:</h1>
            <table>
                <thead>
                    <tr>
                        <th>Поставщик</th>
                        <th>Категория</th>
                        <th>Название модели</th>
                        <th>Цена</th>
                        <th>Статус</th>
                        <th>Убрать из корзины</th>
                    </tr>
                </thead>
                <tbody>
                {% for product in user_cart %}
                    <tr>
                        <td>{{ product.category.shop.name }}</td>
                        <td>{{ product.category.name }}</td>
                        <td>{{ product.model_name }}</td>
                        <td>{{ product.price }}</td>
                        <td>{{ product.status }}</td>
                        <td>
                            <form action="{% url 'remove_from_cart' product.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit">x</button>
                            </form>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="5">Ваша корзина пуста.</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>
</main>
</body>
</html>

diplom/main/templates/base.html
<!-- home.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/Base.css' %}">
    <title>Ваша страница</title>
</head>
<body>

<header>
    <div class="left-links">
        <p>Список товаров</p>
    </div>
    <div class="right-links">
        {% if request.user.is_authenticated %}
            <button><a href="/accounts/profile/">Личный кабинет</a></button>
            <button><a href="logout/">Выйти</a></button>
        {% else %}
            <button><a href="/register/">Регистрация</a></button>
            <button><a href="api/v1/drf-auth/login/">Войти</a></button>
        {% endif %}
    </div>
</header>
<main>
    <h1>Товары</h1>
    <ul>
        {% for good in goods %}
        <li>
            <h2>{{ good.shop.name }}</h2> <!-- Вывод названия магазина -->
            <p>{{ good.name }}</p>
            <p>Цена: {{ good.price }}</p>
            <p>Количество: {{ good.quantity }}</p>
            <p>Параметры: {{ good.formatted_parameters | safe }}</p>
            {% if account_type == 'Покупатель' %}
            <form method="post" action="{% url 'add_to_cart' good.id %}">
                {% csrf_token %}
                <input type="text" name="delivery_address" placeholder="Введите адрес доставки" required>
                <button type="submit">Добавить в корзину</button>
            </form>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
</main>
</body>
</html>

diplom/main/templates/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invoice</title>
</head>
<body>
    <h1>Новый заказ от покупателя</h1>
    <p>Вашему магазину поступил новый заказ от покупателя. Ниже представлен список товаров:</p>
    <ul>
        {% for cart_item in cart_items %}
            <li>{{ cart_item.category }} - {{ cart_item.model }}</li>
        {% endfor %}
    </ul>
    <p>С уважением, ваш магазин</p>
</body>
</html>

diplom/main/templates/good.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/good.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Добавление товара</title>
</head>
<body>

<h1>Добавление товара</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить товар</button>
</form>

</body>
</html>

diplom/main/templates/import_yaml.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/import_yaml.css' %}">
    <title>Import YAML</title>
</head>
<body>
    <h1>Import YAML Data</h1>
    <form method="post" enctype="multipart/form-data" action="{% url 'import-yaml' %}">
        {% csrf_token %}
        <label for="yaml_file" class="custom-file-upload">
            <input type="file" id="yaml_file" name="yaml_file">
        </label>
        <button type="submit">Импортировать</button>
        <button class="button_personal_account"><a href="/accounts/profile/" class="personal_account">Личный кабинет</a></button>
    </form>
</body>
</html>

diplom/main/templates/invoice_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Новый заказ от покупателя</title>
</head>
<body>
    <h2>Новый заказ от покупателя</h2>
    <p>Здравствуйте!</p>
    <p>У вас поступил новый заказ от покупателя. Ниже представлены детали заказанных товаров:</p>
    <ul>
        {% for item in cart_items %}
            <li>
                <p><strong>Категория:</strong> {{ item.category.name }}</p>
                <p><strong>Модель:</strong> {{ item.model_name }}</p>
                <p><strong>Цена:</strong> {{ item.price }}</p>
            </li>
        {% endfor %}
    </ul>
    <p>Пожалуйста, свяжитесь с покупателем для уточнения деталей заказа.</p>
    <p>С уважением,</p>
    <p>Ваш интернет-магазин</p>
</body>
</html>

diplom/main/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/register.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Регистрация</title>
</head>
<body>
    <div class="form-container">
        <form method="post" action="">
            {% csrf_token %}
            <div class="form-row">
                <label for="id_username">Логин:</label>
                {{ form.username }}
            </div>
            <div class="form-row">
                <label for="id_email">E-mail:</label>
                {{ form.email }}
            </div>
            <div class="form-row">
                <label for="id_first_name">Имя:</label>
                {{ form.first_name }}
            </div>
            <div class="form-row">
                <label for="id_last_name">Фамилия:</label>
                {{ form.last_name }}
            </div>
            <div class="form-row">
                <label for="id_password">Пароль:</label>
                {{ form.password }}
            </div>
            <div class="form-row">
                <label for="id_password2">Повтор пароля:</label>
                {{ form.password2 }}
            </div>
            <div class="form-row">
                <label for="id_account_type">Тип аккаунта: Поставщик/Покупатель</label>
                {{ form.account_type }}
            </div>
            <button type="submit">Регистрация</button>
            <a href="{% url 'social_account_signup' %}">Регистрация через Google</a>
        </form>
    </div>
</body>
</html>

diplom/main/templates/supplier_orders.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Заказы поставщика</title>
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/supplier_order.css' %}">
</head>
<body>
<header>
    <h1>Ваши заказы</h1>
    <div class="button-actions">
        <a href="/">Главная</a>
        <a href="/accounts/profile/">Личный кабинет</a>
    </div>
</header>
<main>
    <div class="order-list">
        {% if supplier_orders %}
            <table>
                <thead>
                    <tr>
                        <th>Название модели</th>
                        <th>Статус</th>
                        <th>Имя и фамилия покупателя</th>
                        <th>Id категории</th>
                        <th>Адрес доставки</th>
                        <th>Действия</th> <!-- Добавлено -->
                    </tr>
                </thead>
                <tbody>
                    {% for order in supplier_orders %}
                        <tr>
                            <td>{{ order.model_name }}</td>
                            <td>{{ order.status }}</td>
                            <td>{{ order.user.first_name }} {{ order.user.last_name }}</td>
                            <td>{{ order.category_id }}</td>
                            <td class="Address_street">{{ order.Address_street }}</td>
                            <td>
                                {% if order.status == "Заказ в обработке" %}
                                    <button class="update-status-btn" data-order-id="{{ order.id }}" data-next-status="Заказ отправлен">Отметить как отправлен</button>
                                {% endif %}
                                {% if order.status == "Заказ отправлен" %}
                                    <button class="update-status-btn" data-order-id="{{ order.id }}" data-next-status="Заказ доставлен">Отметить как доставлен</button>
                                {% endif %}
                                <!-- добавьте дополнительные кнопки для других статусов, если нужно -->
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>У вас пока нет заказов.</p>
        {% endif %}
    </div>
</main>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> <!-- Подключаем jQuery -->
<script src="{% static 'main/js/supplier_order.js' %}"></script> <!-- Подключаем наш JavaScript -->
</body>
</html>

diplom/main/templates/user_order_confirmation_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order Confirmation</title>
</head>
<body>
    <h1>Подтверждение заказа</h1>
    <p>Ваш заказ успешно оформлен. Спасибо!</p>
    <h2>Список товаров:</h2>
    <ul>
        {% for item in user_cart %}
            <li>{{ item.category.name }} - {{ item.model_name }} - Цена: {{ item.price }}</li>
        {% endfor %}
    </ul>
</body>
</html>